export const FETCH_CONTINENTS_DATA = 'FETCH_CONTINENTS_DATA';
export const FETCH_COUNTRIES_DATA = 'FETCH_COUNTRIES_DATA';
export const UPDATE_SELECTED_CONTINENT = 'UPDATE_SELECTED_CONTINENT'; 
export const UPDATE_COUNTRIES_TO_DISPLAY_FLAGS = 'UPDATE_COUNTRIES_TO_DISPLAY_FLAGS';